app:
  container_name: <%= dir %>-app
  image: joonasy/wordpress
  links:
    - mysql
  ports:
    - 8000:80
  volumes:
    - ./<%= dir %>:/var/www/html/wp-content/themes/<%= dir %>
    - ./<%= dir %>/wp/composer.json:/var/www/html/composer.json
    - ./wp/wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
    - ./wp/wp-content/plugins:/var/www/html/wp-content/plugins
    - ./wp/wp-content/uploads:/var/www/html/wp-content/uploads
    - ./wp-config.development.php:/var/www/html/wp-config.development.php
  environment:
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: password

mysql:
  container_name: <%= dir %>-mysql
  image: mariadb
  ports:
    - 13306:3306
  environment:
    MYSQL_ROOT_PASSWORD: password
